bookers/config/routes.rb
Rails.application.routes.draw do
  get 'books/new' 
  post 'books' => 'books#create' 
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show' , as:'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  root to: "homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
end

bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers/app/models/book.rb
class Book < ApplicationRecord
    
  validates :title, presence: true
  validates :body, presence: true

end

bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def new
    # Viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    @book = Book.new  
  end
 
 
 


  def create
    @book = Book.new(book_params)
    @books = Book.all  
    if @book.save
      flash[:success] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  
  
  
  
  
  
  
  
  
  
  def index
    @books = Book.all  
    @book = Book.new
  end










  def show
    @book = Book.find(params[:id])  
  end






  def edit
    @book = Book.find(params[:id])
  end
  
  
  
  
  
  
  
  def update
  @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "Book was successfully updated."
      redirect_to @book
    else
      render :edit
    end
  end
  
  
  
  
  
  
  
  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:success] = "Book was successfully deleted."
      redirect_to books_path
    else
      flash[:error] = "Failed to delete the book."
      redirect_to @book
    end
  end







  private
  # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

bookers/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers/app/helpers/books_helper.rb
module BooksHelper
end

bookers/app/helpers/homes_helper.rb
module HomesHelper
end

bookers/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

    <%= form_with model: @book, url:update_book_path(@book.id), method: :patch do |f| %>
    <h1>Editing Book</h1>
   
    <div class="field">
        <label for="book_title">Title</label>
        <%= f.text_field :title %>
    </div>
    
    <div class="field">
        <label for="book_body">Body</label>
        <%= f.text_area :body %>
    </div>

    <div class="actions">
        <%= f.submit 'Update Book' %>
    </div>
    
    <%= link_to "Show", book_path(@book.id) %> | 
        <a href="/books">Back</a>
    

   <% end %>

bookers/app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<% if flash[:success] %>
    <div class="success-message">
        <%= flash[:success] %>
    </div>
<% end %>

        
        <p id="notice"></p>
        <h1>Books</h1>
        <table>
            <thead>
                <tr>
                  <th>Title</th>
                  <th>Body</th>
                  <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
                <% @books.each do |book| %>
                <tr>
                    <td>
                        <span>
                            <%= book.title %>
                        </span>
                    </td>
                    <td>
                        <span>
                             <%= book.body %>
                        </span>
                    </td>
                    <td>    
                        <span>
                                <%= link_to "Show", book_path(book.id) %>
                            
                        </span>
                    </td>

                    <td>
                        <span class="kaka">
                            <%= link_to "Edit", edit_book_path(book.id) %>
                        </span>
                    </td>
                    <td>
                            <span>
                                 <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, remote: true, data: { confirm: "本当に削除しますか？" } %>
                            </span>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
        
   
        
        
        
        
        <h2>New book</h2>
        <%= form_with model: @book, url: '/books', method: :post do |f| %>

            <div class="field">
                <label for="book_title">Title</label>
                <%= f.text_field :title %>
            </div>
            <div class="field">
                <label for="book_body">Body</label>
                <%= f.text_area :body %>
            </div>

            <div class="actions">
                  <%= f.submit 'Create Book' %>
            </div>
          <% end %>

bookers/app/views/books/new.html.erb
<h1>新規投稿</h1>
<!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
	
  <h4>本文</h4>
  <%= f.text_area :body %>
	
  <%= f.submit '投稿' %>
<% end %>

bookers/app/views/books/show.html.erb
<html>

    <body>
        <% if flash[:success] %>
          <div class="success-message">
            <%= flash[:success] %>
          </div>
        <% end %>
        
        
        <p id="notice"></p>
        <p>
          <strong>Title:</strong><%= @book.title %>
        </p>
        <p>
            <strong>Body:</strong><%= @book.body %>
        </p>
        <%= link_to "Edit", edit_book_path(@book.id) %> 
           | 
            <a href="/books">Back</a>
    </body>
</html>

bookers/app/views/homes/top.html.erb
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
            .turbolinks-progress-bar {
                position: fixed;
                display: block;
                top: 0;
                left: 0;
                height: 3px;
                background: #0076ff;
                z-index: 9999;
                transition: width 300ms ease-out, opacity 150ms 150ms ease-in;
                transform: translate3d(0, 0, 0);
                
            }
        </style>
        <link rel="stylesheet" media="all" href="/assets/application-d12397cbc3a266ce5a99f7b588223090c55ca04a439953bb5f9304395de93fc3.css" data-turbolinks-track="reload">
        <script src="/assets/application-114264dd93c8ff30e4335b71eed7949d66c4e7a8eb62e2de6284c046fe07104b.js" data-turbolinks-track="reload"></script>
        <title>WebCampBackendNew</title>
        <meta name="csrf-param" content="authenticity_token">
        <meta name="csrf-token" content="tren47BHIC1DpPa9wkYw/e+NupYlkmkSWEx//ZsEILVf2npdTPiGWbSytB9VwTwOqm6L/9oYTsM1x+PzuffHLQ==">
    </head>
    <body>
    <h1>"ようこそ"<strong>Bookers</strong>"へ！"</h1>
    <p><strong>Bookers</strong>"では、さまざまな書籍に関するあなたの意見や"</p>
    <p>印象を共有し交換することができます</p>
    <p>
       <a href="/books">start</a> 
    </p>
    </body>
</html>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>